services:
  - type: web
    name: startup-ecosystem-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: https://startup-ecosystem-intelligence.replit.app,http://localhost:3000,http://localhost:3001